### ISSUE TITLE
Kurulum Nasıl Yapılıyor?

### ISSUE THREAD

**Issue by berke73** [atilaahmettaner/bollinger-band-screener#5]
Kurulum nasıl yapılıyor acaba. Yardımcı olur musunuz?

**Comment by atilaahmettaner** [comment]
Merhaba, tabi ki bu projeyi local ortamda kullanabilmek için iki farklı yol var:

### 1. Projeyi İndirin
```bash
git clone https://github.com/atilaahmettaner/bollinger-band-screener.git
cd bollinger-band-screener
```

### 2. Gerekli Kütüphaneleri Yükleyin
```bash
pip install -r requirements.txt
```

### 3. Uygulamayı Başlatın
```bash
python app.py
```


- Uygulama otomatik olarak `http://localhost:5000` adresinde başlayacaktır
- Tarayıcınızdan `http://localhost:5000` adresine giderek uygulamayı kullanabilirsiniz
- Uygulamayı durdurmak için terminal üzerinde `Ctrl+C` tuşlarını kullanabilirsiniz


### Farklı  bir alternatif olarak docker kullanarak bu işlemi gerçekleştirebilirsiniz. Docker ile kurulum yapmak, bağımlılıklarla uğraşmadan hızlıca başlamanızı sağlar.
1. Docker Image Oluşturun
```bash
docker build -t cryptoscreener .
```
3. Container'ı Çalıştırın
```bash
docker run -d -p 5000:5000 cryptoscreener
```

**Comment by berke73** [comment]
Hocam teşekkür ederim ama inanın çok acemiyim. Bunu bilgisayar cmd komut sistemi ile mi yapacağım.

**Comment by atilaahmettaner** [comment]
Evet bu işlemi cmd üzerinden yapmanız gerekmektedir.  aşağıdaki adres üzerinden de projeye ulaşabilirsiniz.. 
https://crypto-scanner-app.herokuapp.com/
